### ISSUE TITLE
Respect scheme colors

### ISSUE THREAD

**Issue by Defman21** [babobski/RGBA-Colorpicker#1]
You can stylize your color picker with current color scheme colors.

They are placed at `~/.komodoide/10.0/colors.less` and you can access them in the css with `@import url("resource://profile/colors.less");`

**Comment by babobski** [comment]
By default the skinning of the colorpicker is done trough the js files.
But It's an good idea for the future, to implement some skinning to the colorpicker so it matches you're skin.

**Comment by Defman21** [comment]
#4
