### ISSUE TITLE
Ability to copy/paste colors

### ISSUE THREAD

**Issue by Naatan** [babobski/RGBA-Colorpicker#3]
This is probably a shortcoming in the lib that you use so might not be addressable by you, but in case it is; it would be nice if you could copy/paste color values.

**Comment by babobski** [comment]
Good point, noticed it.
Looked at the colorPicker repo, there is currently a [issue](https://github.com/PitPik/colorPicker/issues/2) open for the paste function.

Played around a little bit, but currently it is not catching these events.
But when I look at the [documentation](https://github.com/PitPik/colorPicker#the-color-model-the-methods-and-more), you can add you're custom events.
So I think its possible to get it working, will look in to it.

**Comment by babobski** [comment]
@Naatan added the copy, pase and cut functionality.

p.s. All action also work without any selection, you can just put the cursor in the input for these action to work.
